version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Mount code for live updates

    env_file:
      - ./backend/.env
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  scraper:
    build:
      context: ./scraper
    env_file:
      - ./scraper/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Mount code for live updates
    env_file:
      - ./frontend/.env
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
