version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
  
  scraper:
    build:
      context: ./scraper
    env_file:
      - ./scraper/.env
    environment:
      - DATA_PATH=/app/scraper/data  # Override the DATA_PATH variable

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env

    command: ["npm", "run", "build"]

