from decouple import config

DATA_PATH = config("DATA_PATH")
NO_STORE_DATA=False
NO_CACHE_DATA=False

DATABASE_URL = config("DATABASE_URL")
POSTGRES_USER = config("POSTGRES_USER")
POSTGRES_PASSWORD = config("POSTGRES_PASSWORD")
POSTGRES_DB = config("POSTGRES_DB")
POSTGRES_HOST = config("POSTGRES_HOST")